import Head from "next/head";
import "./globals.css";
import Navbar from "./components/Navbar"

export const metadata = {
  title: "7Janpath Forex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
